# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: 
        slider:
            quality: 80
            filters: 
                upscale: 
                    min: [800,400]
                thumbnail: 
                    size: [800,400]
                    mode: outbound
        sliderbackoffice:
            quality: 80
            filters: 
                upscale: 
                    min: [320,200]
                thumbnail: 
                    size: [320,200]
                    mode: outbound
        article:
            quality: 80
            filters: 
                upscale: 
                    min: [240,240]
                thumbnail: 
                    size: [240,240]
                    mode: outbound
        searcharticle:
            quality: 100
            filters: 
                upscale: 
                    min: [128,128]
                thumbnail: 
                    size: [128,128]
                    mode: outbound
        articledescription:
            quality: 80
            filters: 
                upscale: 
                    min: [900,900]
                thumbnail: 
                    size: [900,900]
                    mode: outbound
        marque:
            quality: 80
            filters: 
                upscale: 
                    min: [224,224]
                thumbnail: 
                    size: [224,224]
                    mode: outbound

