# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: 
        slider:
            quality: 80
            filters: 
                upscale: 
                    min: [800,400]
                thumbnail: 
                    size: [800,400]
                    mode: outbound
        article:
            quality: 80
            filters: 
                upscale: 
                    min: [240,240]
                thumbnail: 
                    size: [240,240]
                    mode: outbound
        marque:
            quality: 80
            filters: 
                upscale: 
                    min: [240,240]
                thumbnail: 
                    size: [240,240]
                    mode: outbound

